(cons (eq? 3 3)
(cons (eq? 4 5)
(cons (eq? 'a 'a)
(cons (eq? char? char?)
(cons (eq? #t #t)
(cons (eq? '() '())
(cons (eq? (char? 1) (char? 2))
(cons (or (eq? '#(1 2 3) '#(1 2 3)) (not (eq? '#(1 2 3) '#(1 2 3))))
(cons (or (eq? '(1 2 3) '(1 2 3)) (not (eq? '(1 2 3) '(1 2 3))))
(cons (eq? (symbol->string 'a) "a")
	'()))))))))))