(cons (char->integer #\-) 
(cons (char->integer #\#) 
(cons (char->integer #\") 
(cons (integer->char 67) 
(cons (integer->char (char->integer #\X))  
(cons (symbol->string 'ab)
(cons (string->symbol "abc")
(cons (string->symbol "null?")
(cons (procedure? (string->symbol "null?"))
	'())))))))))