(define vec (make-vector 3 #t))
(vector-set! vec 2 #t)
(vector-set! vec 1 #f)
(vector-set! vec 0 '#(1 2 3))

(cons (equal? vec '#(#(1 2 3) #f #t))
(cons (vector-length '#(1 2 3)) 
(cons (vector-length '#(1 2 #(1 2 4))) 
(cons (vector-length '#()) 
(cons (vector-length (make-vector 4 #t)) 
(cons (vector-length (make-vector 0 0)) 
(cons (vector-ref '#(1 2 3) 0) 
(cons (vector-ref '#(1 2 3) 2) 
(cons (vector-ref (make-vector 100 "b") 99) 
	'())))))))))